version: '3.1'

services:
  db:
    image: postgres
    shm_size: '4gb'
    container_name: confab
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - confab
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  confab:
    name: confab

volumes:
  postgres:
    driver: local
