@url = http://localhost:5000/conferences-module
@id = c3e173ba-17e5-418d-bcd1-797bf823f8a2
@hostId = d9921cc0-55cf-427a-85a5-244424fb6063
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZmNmZDg1Ny1hY2FmLTQzYWEtYTUyZi1lMjRhNmI2YjgwZmIiLCJ1bmlxdWVfbmFtZSI6IjlmY2ZkODU3LWFjYWYtNDNhYS1hNTJmLWUyNGE2YjZiODBmYiIsImp0aSI6ImVlYzJkMzBiLWMwYzAtNDgwYy04NWYyLWNlYjFkZjUyNzY5OCIsImlhdCI6IjE2ODYwNjQ1NDYwMDMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTY4NjA2NDU0NiwiZXhwIjoxNjg2MTAwNTQ2LCJpc3MiOiJjb25mYWIifQ.ucEFtyQ1gCXBLaAA7GGgwwvwG8Sv-ChGt-A1LQuPHJA

# Conferences - Conference GET ALL
###
Get {{url}}/conference

# Conferences - Conference GET by id
###
Get {{url}}/conference/{{id}}

# Conferences - Conference POST
###
POST {{url}}/conference
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "hostname": "John Lemon",
    "hostid": "{{hostId}}",
    "Name": "My first conference",
    "Location": "Poland",
    "description": "Long description",
    "from": "2026-01-05",
    "to": "2026-01-06",
    "participantsLimit": 100,
    "logoUrl": null
}

# Conferences - Conference UPDATE
###
PUT {{url}}/conference/{{id}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "Name": "My first conference",
    "description": "Long description",
    "logoUrl": "www.logo.com",
    "location": "Poland",
    "from": "2026-01-05",
    "to": "2026-01-06",
    "participantsLimit": 120
}

# Conferences - Conference DELETE
###
DELETE {{url}}/conference/{{id}}
Authorization: Bearer {{accessToken}}
