@url = http://localhost:5000/conferences-module
@id = de47a7fa-91bc-4c92-bf53-469b0bd86f84

# REMEMBER TO SignIn and use access token

# Conferences - Host GET ALL
###
Get {{url}}/host

# Conferences - Host GET by id
###
Get {{url}}/host/{{id}}

# Conferences - Host POST
###
POST {{url}}/host
Content-Type: application/json

{
    "name": "John Doe 2",
    "description": "Long description"
}

# Conferences - Host UPDATE
###
PUT {{url}}/host/{{id}}
Content-Type: application/json

{
    "Name": "John Lemon",
    "description": "Long description2"
}

# Conferences - Host DELETE
###
DELETE {{url}}/host/{{id}}
