@url = http://localhost:5000/conferences-module
@id = d5a87351-5875-4aa7-b253-e22d9a3ec5d5

# Conferences - Conference GET ALL
###
Get {{url}}/conference

# Conferences - Conference GET by id
###
Get {{url}}/conference/{{id}}

# Conferences - Conference POST
###
POST {{url}}/conference
Content-Type: application/json

{
    "hostname": "John Lemon",
    "hostid": "de47a7fa-91bc-4c92-bf53-469b0bd86f84",
    "Name": "My first conference",
    "Location": "Poland",
    "description": "Long description",
    "from": "2026-01-05",
    "to": "2026-01-06",
    "participantsLimit": 100,
    "logoUrl": null
}

# Conferences - Conference UPDATE
###
PUT {{url}}/conference/{{id}}
Content-Type: application/json

{
    "Name": "My first conference",
    "description": "Long description",
    "logoUrl": "www.logo.com",
    "location": "Poland",
    "from": "2026-01-05",
    "to": "2026-01-06",
    "participantsLimit": 120
}

# Conferences - Conference DELETE
###
DELETE {{url}}/conference/{{id}}
